<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNO43cLE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNO43cLE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNO43cLE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNO43cLE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNO43cLE\App_KernelDevDebugContainer([
    'container.build_hash' => 'NO43cLE',
    'container.build_id' => 'd2a9d4e8',
    'container.build_time' => 1610660164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNO43cLE');
